### ISSUE TITLE
1.18.x code reliably crashes client on clicking "key binds" button

### ISSUE THREAD

**Issue by ewe2** [irtimaled/BoundingBoxOutlineReloaded#151]
1. build dev code from source, standard gradle build.
2. . run with a 1.18.x client, I use MultiMC on a linux platform to run 1.18.1
3. click options, controls, keybinds, BOOM
4. it is not necessary to have any other key-management mod as I thought at first, it will do this from the front screen.

Here is a backtrace for you:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 20/3/22, 7:57 am
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.compareTo(java.lang.Integer)" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.class_304.method_1430(class_304.java:135)
	at com.irtimaled.bbor.client.keyboard.CustomKeyBinding.compareTo(CustomKeyBinding.java:6)
	at java.base/java.util.ComparableTimSort.binarySort(ComparableTimSort.java:262)
	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:207)
	at java.base/java.util.Arrays.sort(Arrays.java:1041)
	at net.minecraft.class_459.<init>(class_459.java:33)
	at xyz.starmun.justenoughkeys.common.gui.JEKControlList.<init>(JEKControlList.java:34)
	at xyz.starmun.justenoughkeys.common.gui.JEKControlScreen.method_25426(JEKControlScreen.java:41)
	at net.minecraft.class_437.method_25423(class_437.java:388)
	at net.minecraft.class_310.method_1507(class_310.java:989)
	at net.minecraft.class_458.method_19872(class_458.java:27)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:220)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_304.method_1430(class_304.java:135)
	at com.irtimaled.bbor.client.keyboard.CustomKeyBinding.compareTo(CustomKeyBinding.java:6)
	at java.base/java.util.ComparableTimSort.binarySort(ComparableTimSort.java:262)
	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:207)
	at java.base/java.util.Arrays.sort(Arrays.java:1041)
	at net.minecraft.class_459.<init>(class_459.java:33)
	at xyz.starmun.justenoughkeys.common.gui.JEKControlList.<init>(JEKControlList.java:34)
	at xyz.starmun.justenoughkeys.common.gui.JEKControlScreen.method_25426(JEKControlScreen.java:41)
	at net.minecraft.class_437.method_25423(class_437.java:388)
	at net.minecraft.class_310.method_1507(class_310.java:989)
	at net.minecraft.class_458.method_19872(class_458.java:27)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_458
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:220)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Default, Fabric Mods, CreatorPack-1.18-V1.2.2.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.16.0-3-amd64
	Java Version: 17.0.2, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
	Memory: 3754847192 bytes (3580 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: GP107 [GeForce GTX 1050 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 27601.91
	Virtual memory used (MB): 16967.92
	Swap memory total (MB): 14847.99
	Swap memory used (MB): 2857.27
	JVM Flags: 20 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xms4096m -Xmx4096m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		ae2: Applied Energistics 2 10.0.0
		architectury: Architectury 3.7.22
		attributefix: AttributeFix 13.0.5
		balm-fabric: Balm 2.4.3+0
		bbor: BoundingBoxOutlineReloaded 2.4-1.18.1
		blue_endless_jankson: jankson 1.2.1
		cardinal-components: Cardinal Components API 4.1.3
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.1.3
		cardinal-components-chunk: Cardinal Components API (chunks) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.1.3
		cardinal-components-level: Cardinal Components API (world saves) 4.1.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.3
		cardinal-components-world: Cardinal Components API (worlds) 4.1.3
		carrier: Carrier 1.9.0
		clientcommands: Client Commands 2.6
		clientcommands-scripting: Clientcommands Scripting 1.3
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		ec-core: Essential Commands Core 1.0.1-mc1.18.1
		editsign: EditSign 2.2.7
		essential_commands: Essential Commands 0.20.2-mc1.18.1
		expandedstorage: Expanded Storage 7.3.9
		explorerscompass: Explorer's Compass 1.18.1-2.0.2-fabric
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.3
		fallingtree: FallingTree 3.2.1
		flytre_lib: FlytreLib 1.7.1
		forgeconfigapiport: Forge Config API Port 3.1.0
		inventoryessentials: Inventory Essentials 4.0.0
		inventorysorter: Inventory Sorter 1.8.4-1.18
		java: OpenJDK 64-Bit Server VM 17
		justenoughkeys: Just Enough Keys 0.5.3
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		lightoverlay: Light Overlay 6.0.4
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		mousetweaks: Mouse Tweaks 2.18
		multiconnect-api: MultiConnect API 1.5
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.6
		pipe: Pipe 1.6.2
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.3.0
		roughlyenoughitems: Roughly Enough Items 7.0.352
		team_reborn_energy: Energy 2.2.0
		theoneprobe: The One Probe 1.18-5.0.6
		travelersbackpack: Traveler's Backpack 1.18.1-7.0.0
		underwaterrails: Underwater Rails 2.3.0
		worldedit: WorldEdit 7.2.8+6008-1246d61
		worldeditcui: WorldEditCUI 1.18.1+01-SNAPSHOT
		xaerominimap: Xaero's Minimap 22.2.0.1
		xaeroworldmap: Xaero's World Map 1.20.3.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 470.103.01, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/CreatorPack-1.18-V1.2.2.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/ewe2/minecrafts/MultiMC/instances/1.18.1/.minecraft/crash-reports/crash-2022-03-20_07.57.17-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

**Comment by ishland** [comment]
Fixed in recent devbuilds.
