### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Andavin** [irtimaled/BoundingBoxOutlineReloaded#32]
My client crashes every time I start it with the LiteLoader version. Forge version starts up and works fine, but client crashes. I'm using a Forge/LiteLoader profile combination LiteLoader 1.12.2 release and Forge 1.12.2-14.23.1.2555.

```
09:25:38 | game | [15:25:38] [main/FATAL]: Mixin apply failed mixins.bbor.json:MixinKeyBinding -> net.minecraft.client.settings.KeyBinding: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Overwrite target "a" was not located in target class net/minecraft/client/settings/KeyBinding
09:25:38 | game | org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "a" was not located in target class net/minecraft/client/settings/KeyBinding
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:463) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:425) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:407) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:299) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_74]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_74]
09:25:38 | game | at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) [bib.class:?]
09:25:38 | game | at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
09:25:38 | game | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
09:25:38 | game | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
09:25:38 | game | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
09:25:38 | game | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
09:25:38 | game | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
09:25:38 | game | at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.bbor.json:MixinKeyBinding] from phase [DEFAULT] in config [mixins.bbor.json] FAILED during APPLY
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Method.java:498)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
09:25:38 | game | [15:25:38] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "a" was not located in target class net/minecraft/client/settings/KeyBinding
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:463)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:425)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:407)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:299)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 13 more
09:25:38 | game | [15:25:38] [main/ERROR]: Unable to launch
09:25:38 | game | java.lang.reflect.InvocationTargetException: null
09:25:38 | game | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
09:25:38 | game | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
09:25:38 | game | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
09:25:38 | game | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
09:25:38 | game | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
09:25:38 | game | at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
09:25:38 | game | Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraft/client/settings/KeyBinding
09:25:38 | game | at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
09:25:38 | game | at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
09:25:38 | game | ... 6 more
09:25:38 | game | Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/settings/KeyBinding
09:25:38 | game | at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
09:25:38 | game | at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
09:25:38 | game | ... 6 more
09:25:38 | game | Caused by: java.lang.ClassNotFoundException: net.minecraft.client.settings.KeyBinding
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
09:25:38 | game | at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
09:25:38 | game | at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
09:25:38 | game | ... 6 more
09:25:38 | game | Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
09:25:38 | game | at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
09:25:38 | game | at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
09:25:38 | game | ... 6 more
09:25:38 | game | Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.bbor.json:MixinKeyBinding] from phase [DEFAULT] in config [mixins.bbor.json] FAILED during APPLY
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
09:25:38 | game | at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
09:25:38 | game | at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
09:25:38 | game | ... 6 more
09:25:38 | game | Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "a" was not located in target class net/minecraft/client/settings/KeyBinding
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:463) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:425) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:407) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:299) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[liteloader-1.12.2-SNAPSHOT.jar:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
09:25:38 | game | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
09:25:38 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
09:25:38 | game | at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
09:25:38 | game | at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
09:25:38 | game | ... 6 more
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
09:25:38 | game | [15:25:38] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by irtimaled** [comment]
I didn't test with the combination of Forge and Liteloader.  The mod works fine on LiteLoader 1.12.2-SNAPSHOT-r4CC2BB0-b4-4 and the failing Mixin patches a problem in Vanilla that breaks the controls section of Minecraft - perhaps Forge have changed their implementation.

**Comment by Andavin** [comment]
I see. Well if it works fine with just LiteLoader then I guess it's something to do with the Forge/LiteLoader combo. I've had issues with them using different version of ASM in the past and such so maybe it's something to do with that.

**Comment by irtimaled** [comment]
Looks like Forge replaces the KeyBinding class with one that doesn't have a compareTo method.  Is using LiteLoader with Forge something that happens alot?

**Comment by Andavin** [comment]
There are a good amount of tutorials on it and it's the only configuration I use since I like using all types of mods. I'm not sure how common it is, but I'd guess it's moderately common.

**Comment by irtimaled** [comment]
I guess if you wish to use BBOR with Forge & LiteLoader the best option is to use it with Forge online.  I'll look into conditional Mixins and if I get a fix I'll close this issue

**Comment by irtimaled** [comment]
I have changed how this is done in 1.13+ which should not cause this issue when Forge 1.13 & LiteLoader 1.13 are released
