### ISSUE TITLE
Exception thrown during Spigot server startup

### ISSUE THREAD

**Issue by rhullah** [irtimaled/BoundingBoxOutlineReloaded#50]
**Versions:**
Spigot Server: `git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`
BBOR Server: `BBOutlineReloaded-1.0.10-1.13.2-bukkit.jar`
BBOR Client: `BBOutlineReloaded-1.0.10-1.13.2-rift.jar`
(The client version is really irrelavant, but I thought I'd include it)

I noticed while starting my Spigot server with the plugin present that the server throws an exception right before the server is brought online:

```
>2019-05-02 12:00:02,277 Server thread ERROR Could not find class in ReflectionUtil.getCallerClass(2). java.lang.ClassNotFoundException: com.irtimaled.bbor.Logger
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:141)
        at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:141)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
        at com.irtimaled.bbor.Logger.<clinit>(Logger.java:6)
        at com.irtimaled.bbor.common.CommonProxy.worldLoaded(CommonProxy.java:65)
        at com.irtimaled.bbor.common.EventBus.publish(EventBus.java:17)
        at com.irtimaled.bbor.bukkit.Events.onWorldLoad(Events.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:518)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Weird thing is that it seems that everything still continues to work: I can view bounding boxes from the client when connected to the server..  I'm not sure if that's a good thing or something is still going wrong in the background.

It looks like the internals of the static method `LogManager.getLogger()` on [line 6](/irtimaled/BoundingBoxOutlineReloaded/blob/c4e9553b842f064a3a0bd7f2cb4a8845e536435c/src/main/java/com/irtimaled/bbor/Logger.java#L6) is what's throwing the issue.  Which is weird since it seems like it can't find the class that it's being called from.

**Comment by irtimaled** [comment]
Not sure what I can do about this.  If this actually causes anything more than noise in the logs then please re-open this issue.
