### ISSUE TITLE
Can't make server 1.14.2 vanilla

### ISSUE THREAD

**Issue by GZQ65** [irtimaled/BoundingBoxOutlineReloaded#60]
When I run the jar this warning comes up:

Exception in thread "main" java.lang.NullPointerException
        at com.irtimaled.bbor.server.ServerRunner.getOrDownload(ServerRunner.java:70)
        at com.irtimaled.bbor.server.ServerRunner.run(ServerRunner.java:56)
        at com.irtimaled.bbor.Main.main(Main.java:12)

**Comment by irtimaled** [comment]
Ahh yeah - spotted I’d missed the 1.14.2 jar location for the build I pushed to curseforge. Will upload a new version soon

**Comment by GZQ65** [comment]
Ok great

**Comment by OzanKurt** [comment]
@irtimaled Any updates about this?
